### ISSUE TITLE
Idk if I'm stupid, But i cant find the file the run the moosic bot

### ISSUE THREAD

**Issue by MrRay70915** [Repulser/Moosic#1]

**Comment by AnorexicTramp** [comment]
Hey! looks like you pulled the sourcecode and not the zip! See below:
![image](https://user-images.githubusercontent.com/24868366/27297509-017e4148-551d-11e7-93e5-5283b008cdad.png)

https://github.com/Repulser/Moosic/releases/

Should look like this once you've extracted it!
![image](https://user-images.githubusercontent.com/24868366/27297488-ec434a26-551c-11e7-92e8-8978c5d72263.png)
