### ISSUE TITLE
Setting it up?

### ISSUE THREAD

**Issue by Wardoe** [Repulser/Moosic#11]
I can't set it up, there is no bot.ctg , song.txt , am I doing something wrong or what?

**Comment by MattIPv4** [comment]
I suggest following the setup guide linked in https://github.com/Repulser/Moosic/blob/master/README.md

**Comment by Wardoe** [comment]
I tried but don't get it , hem, im doing something wrong.

**Comment by MattIPv4** [comment]
Well if you followed it and downloaded all the files as it tells you to, you'd have the `bot.ctg` and `songs.txt` files.

**Comment by Wardoe** [comment]
I download bot and song file from here (https://github.com/Repulser/Moosic/releases/) and put it in Moosic file?

**Comment by MattIPv4** [comment]
Follow the setup guide. It explains it all.

**Comment by Wardoe** [comment]
Oke , thanks Ill try it again

**Comment by Repulser** [comment]
@Wardoe the template `bot.cfg` and `songs.txt` files are also located in the assets of the release where you got the jar file.

**Comment by Wardoe** [comment]
I downloaded it , and now its working (On my own) but i don't know how to setup up heroku (after installing heroku step)
!

**Comment by MattIPv4** [comment]
We aren't a support service here. We have provided guides for setting this up, please follow them.

**Comment by Repulser** [comment]
I dont recommend using heroku hence i do not support it, a very cheap vps will do the job far better.

**Comment by Wardoe** [comment]
I want to try heroku first, but could just atleast tell me name of cmd in moosic folder cuz i can't write in any of them? Meh im stupid. xD

**Comment by Repulser** [comment]
Shift + right click a blank space and click open command window here, For any further questions you should ask in the support guild, https://discord.gg/cf3tNMW
