### ISSUE TITLE
No text interaction

### ISSUE THREAD

**Issue by Ertuit** [Repulser/Moosic#14]
Hello, 
I have installed and configured the "config. cfg" file of the last vertion of the bot, the 5.1.
But I can't interact with the bot! 
I set my prefix to this character: <    
My bot.cfg file : https://pastebin.com/BuviXNs6
In the private messages it shows me this : https://pastebin.com/mG8umV9a
Thank you:)
Ertuit

**Comment by Repulser** [comment]
That second paste does not seem to be related, this is not a music bot, the only command it has is to view the current playing song (np).

**Comment by Ertuit** [comment]
Thank you very much,
But in a previous vertion there was more command such as "skip","play" etc....
PS : <np works well :)

**Comment by GreggKr** [comment]
Are you possibly talking about Rythm?
