### ISSUE TITLE
Is there a loop command?

### ISSUE THREAD

**Issue by randal923** [Repulser/Moosic#17]
Hi, sorry if I'm posting in the wrong section. But I would like to play 1 song in loop 24/7. Is that possible?

**Comment by KJP12** [comment]
Yes, it is. You will have to reload the bot with the songs.txt being the song you want to loop 24/7.

For example, you want to have [Tristam - Party for the Living](https://www.youtube.com/watch?v=ksQbpP9v88Q) playing 24/7, all you need in songs.txt is this:
`https://www.youtube.com/watch?v=ksQbpP9v88Q`

As for looping the current song playing and without reloading the bot, that isn't possible

**Comment by Repulser** [comment]
Overcomplicating ^ just have the 1 song you want in songs.txt :)

**Comment by tezcalitpoka** [comment]
i have 1 playlist link in song.txt which has 120 songs, but how can i play that playlist non-stop? its stopping after playin all.
