### ISSUE TITLE
My bot won't come online at all.

### ISSUE THREAD

**Issue by Craixzo** [Repulser/Moosic#30]
My bot still won't come online. I did all the steps for the 1st guide and it didn't work. I tried using heroku and it didn't work. I tried a ton of other stuff and it didn't work. I am running this on Linux. What am I missing?

**Comment by Craixzo** [comment]
wait nevermind I'm just too stupid to realize what I did wrong

**Comment by Repulser** [comment]
Are you able to post the output from where you run the bot?
