### ISSUE TITLE
[Question] Changing the playing status

### ISSUE THREAD

**Issue by TheSilentPro** [Repulser/Moosic#35]
How do i change the playing status? I can't find the piece of code in it, am i just blind?

**Comment by Repulser** [comment]
Please take a look at https://github.com/Repulser/Moosic/blob/master/src/main/java/co/moosic/music/TrackScheduler.java#L124

**Comment by TheSilentPro** [comment]
Ah, thank you. Didn't see it. 
Sorry for the bother, is there a main discord you have?

**Comment by Repulser** [comment]
You may join my server at https://discord.gg/rythm and dm me - ImBursting#0051
