### ISSUE TITLE
Broken :/ 

### ISSUE THREAD

**Issue by Sivonja8** [Repulser/Moosic#44]
[ INFO ] [Reflections] Reflections took 232 ms to scan 1 urls, producing 1 keys and 5 values 
[ INFO ] [Reflections] Reflections took 2145 ms to scan 1 urls, producing 1989 keys and 10344 values 
Enabling native audio sending
[ WARN ] [RateLimiter] Encountered 429 on route /gateway

**Comment by Repulser** [comment]
Your IP is being ratelimited by Discord. Please wait a short while and try again if you see this issue.
